# Generated by Django 3.1.4 on 2021-01-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_content',
            field=models.CharField(default=models.TextField(), max_length=300),
        ),
    ]
